### ISSUE TITLE
Readlink usage not compatible with macOS

### ISSUE THREAD

**Issue by p4tpr0** [trimstray/mkchain#5]
Current use of command **readlink** in shell script code is not compatible with macOS:
- install fails
- execution fails

sample error upon execution:
`readlink: illegal option -- f
usage: readlink [-n] [file ...]
/usr/local/bin/sslmerge: line 57: ./../src/settings: No such file or directory
/usr/local/bin/sslmerge: line 59: ./../src/helpers: No such file or directory
/usr/local/bin/sslmerge: line 61: ./../src/__init__: No such file or directory
/usr/local/bin/sslmerge: line 66: __main__: command not found
/usr/local/bin/sslmerge: line 68: _exit_: command not found
`

**Comment by trimstray** [comment]
Hi!

It's true that there is a problem with readlink on macos and freebsd.

1) I'll check what can be done with it.
2) I added information on what platform it works: **[Requirements](https://github.com/trimstray/sslmerge#requirements)**

**Comment by trimstray** [comment]
`greadlink` from **coreutils** package is alternative (tested on FreeBSD).

**Comment by rebtoor** [comment]
> `greadlink` from **coreutils** package is alternative (tested on FreeBSD).

Also work on MacOS with `greadlink` from **coreutils** (installed via homebrew)

**Comment by rebtoor** [comment]
There are other issues with `getopt` (fixed on MacOS using absolute path to the `getopt` binary provided by **gnu-getopt** homebrew package) and `md5sum` (on Mac/FreeBSD there is `md5` tool).

**Comment by trimstray** [comment]
* replace for getopt(1) that supports GNU-style long options (`pkg install getopt`)
* also work on MacOS with `greadlink` from **coreutils** (installed via homebrew)
